from fastapi import APIRouter, Request, HTTPException
from fastapi.responses import StreamingResponse
from models.schema import TTSRequest
from brain.tts_engine import TTSEngine

router = APIRouter(tags=["voice"])

@router.post(
    "/tts-stream",
    summary="Real-Time Streaming TTS",
    description=(
        "### Internal Logic\n"
        "Uses the Gemini 2.5 Flash Multimodal Live API via WebSockets. It maps the `speed` parameter to linguistic pacing prompts "
        "sent in the system instruction. Chunks of raw PCM audio are streamed back as they are generated by the model.\n\n"
        "### Usage Guide\n"
        "Send the text from your current message. On the frontend, use a streaming-capable player (like `fetch` with a `ReadableStream` or an `AudioContext` buffer) "
        "to play the 24kHz Mono PCM audio with zero latency.\n\n"
        "### Scenarios\n"
        "- **Hands-Free Reading**: Converting the current Telegram post into live speech."
    )
)
async def tts_stream(request: Request, req: TTSRequest):
    """
    Streams TTS audio in real-time.
    Input: text, voice, speed.
    Output: audio/pcm stream (24kHz, 16-bit, mono).
    """
    tts_engine: TTSEngine = request.app.state.tts_engine
    
    if not req.text.strip():
        raise HTTPException(status_code=400, detail="Text cannot be empty.")

    return StreamingResponse(
        tts_engine.stream_tts(req.text, req.voice, req.speed),
        media_type="audio/pcm"
    )
